@ADP.Portal.Api_HostAddress = https://localhost:7280

# ADO Controller
GET {{ADP.Portal.Api_HostAddress}}/api/adoproject/string

# AD Group Controller
###
GET {{ADP.Portal.Api_HostAddress}}/api/aadgroup/get/ffc-demo

###
POST {{ADP.Portal.Api_HostAddress}}/api/aadgroup/create/ffc-demo
Content-Type: application/json

{
	"members": [
		"xxx@xxx.onmicrosoft.com"
	]
}

###
PUT {{ADP.Portal.Api_HostAddress}}/api/aadgroup/sync/ffc-demo/UserGroupsMembers

# Flux Config Controller
###
# Create a team
POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo
Content-Type: application/json

{
  "ProgrammeName": "ffc",
  "ServiceCode": "test-demo",
  "TeamName": "test-demo",
  "Services": [
  ],
  "ConfigVariables": {
    "TEAM_CPU_QUOTA": "2000",
    "TEAM_MEMORY_QUOTA": "3000Mi",
    "TEAM_PODS_QUOTA": "20"
  }
}

###

# Update a team
PUT {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo
Content-Type: application/json

{
  "ProgrammeName": "ffc",
  "ServiceCode": "test-demo",
  "TeamName": "test-demo",
  "Services": [
  ],
  "ConfigVariables": {
    "TEAM_CPU_QUOTA": "2000",
    "TEAM_MEMORY_QUOTA": "3000Mi",
    "TEAM_PODS_QUOTA": "20"
  }
}

###
# Helm only ingress app
POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo/services
Content-Type: application/json

{
    "Name": "test-ingress-3",
    "IsFrontend": true,
    "IsHelmOnly": true,
    "Environments": [
        "snd1",
        "snd2",
        "snd3"
    ],
    "ConfigVariables": {}
}

###
# Generate flux service manifest for helm only app
POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo/generate?serviceName=test-ingress-3

###
# Frontend app
POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo/services
Content-Type: application/json

{
    "Name": "ffc-frontend-2",
    "IsFrontend": true,
    "Environments": [
        "snd1",
        "snd2",
        "snd3"
    ],
    "ConfigVariables": {}
}

###

POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo/generate?serviceName=ffc-frontend-2

###
# Backend app
POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo/services
Content-Type: application/json

{
    "Name": "ffc-backend-2",
    "IsFrontend": false,
    "Environments": [
        "snd1",
        "snd2",
        "snd3"
    ],
    "ConfigVariables": {
        "POSTGRES_DB":"test-demo-backend"
    }
}

###

POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/test-demo/generate?serviceName=ffc-backend-2
###
GET {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/get/ffc-demo

###
POST {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/create/ffc-find
Content-Type: application/json
Api-Version: 1.0

{
  "ProgrammeName": "ffc",
  "ServiceCode": "ffc-find",
  "Services": [
    {
      "Name": "ffc-find-web",
      "IsFrontend": false,
      "Environments": [
        "snd1",
        "snd2",
        "snd3"
      ],
      "ConfigVariables": {
        "INGRESS_ENDPOINT": "ffc-find-web"
      }
    }
  ],
  "ConfigVariables": {
    "TEAM_CPU_QUOTA": "2000"
  }
}

###
PUT {{ADP.Portal.Api_HostAddress}}/api/fluxteamconfig/update/ffc-find
Content-Type: application/json

{
  "ProgrammeName": "ffc",
  "ServiceCode": "ffc-find",
  "Services": [
    {
      "Name": "ffc-find-web",
      "IsFrontend": true,
      "Environments": [
        "snd1",
        "snd2",
        "snd3"
      ],
      "ConfigVariables": {
        "INGRESS_ENDPOINT": "ffc-find-web"
      }
    }
  ],
  "ConfigVariables": {
    "TEAM_CPU_QUOTA": "2000"
  }
}

###
